version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data # Сохраняем данные базы
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Первоначальная инициализация
    env_file:
    - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: # Объявляем внешний том для данных
